main: com.backwardsnode.survivalgames.Plugin
name: SurvivalGames
version: ${version}
description: Survival Games plugin for Bukkit
author: IballisticBoss
api-version: 1.18
softdepend: [ProtocolLib,PlaceholderAPI,Vault]